# Generated by Django 2.2.4 on 2022-06-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Desc',
            new_name='desc',
        ),
    ]
